version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Marseille100
      MYSQL_DATABASE: gestion_stock
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  microservice-produits:
    build: .
    container_name: microservice-produits
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_stock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Marseille100
    ports:
      - "8081:8081"
    networks:
      - mynetwork

networks:
  mynetwork: