name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/SerigneBassirou

      # Étape 2 : Configurer Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : Construire et tester le projet avec Maven
      - name: Build and Test with Maven
        run: mvn clean package