name: Build and Test Java Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up JDK 21 with Maven
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'

      - name: Afficher la structure du projet
        run: ls -R

      - name: Build with Maven
        run: mvn clean install